### ISSUE TITLE
Organizing the data directory

### ISSUE THREAD

**Issue by jimmyliu1326** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#15]
Is it necessary to have all those files under data/ ? Our script only really make use of two files under data/

**Comment by HJMcSorley** [comment]
fair point... the file management structure was really just based on the assignment layout and direction/suggestions from the [STAT547 page](https://stat545.stat.ubc.ca/evaluation/milestone_02/milestone_02/). I figure we can stick with it, even though it's not a very robust or diverse directory. It's a good general structure for file management.

**Comment by jimmyliu1326** [comment]
Well it's certainly much cleaner now after we ran make clean haha
