### ISSUE TITLE
updates, accidentally accepted my own PR

### ISSUE THREAD

**Issue by HJMcSorley** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#25]
Hey @jimmyliu1326 

Sorry -- I accidentally accepted my own PR 🤦‍♀ 

I updated the assignment of doc from right arrow (-> doc) to left (doc <-) which seems to have solved the issues I was having running the scripts before. I also added a 'figures' folder for outputs. 

I'm working on loading the data from a URL but it's not working yet 😢

**Comment by jimmyliu1326** [comment]
hey, have you managed to get the script to work yet? Happy to help you with it :) You can use the ```download.file(url, output_path)``` function to read in url and download the data to a specified directory.

**Comment by HJMcSorley** [comment]
Thanks for your help, I'm a noob. I am fighting a thesis draft deadline right now and won't be able to look at it again until tomorrow. I'm sorry. Thank goodness for the grace period, I need it. 

I will try ```download.file(url, output_path)``` tomorrow. I was using ```read_csv(url)``` and ```write_csv()``` but this sounds much better.

**Comment by jimmyliu1326** [comment]
It's all good, good luck with your thesis writing! 

And yah, ```read_csv``` likely doesn't work since it only reads local files.
