### ISSUE TITLE
Feedback assignment

### ISSUE THREAD

**Issue by Nima-Jamshidi** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#30]
- I think to stick to .CSV format is better as suggested by Firas. in `load_data.R` you could have used `datafile <- read_csv(data_url)` and `write_csv(datafile, opt$output)`. `opt$output` in this way should be `"data/downloaded_datafile.csv"` instead of `data/downloaded_datafile`. 
- Why are there two different data_processing approaches? I believe that our goal is to have a reproducible project that someone can start to run them from scratch. Therefore, I do not see the use for `data_processing.R`. `data_processing2.R` would suffice and would not confuse the users. This critique also applies to further scripts including the visualization section.
- I really like the notes that get printed while running the scripts. 
- The readme file is helpful.

**Comment by jimmyliu1326** [comment]
Hi Nima,

Thanks for your feedbacks! We have now combined the `data_processing.R` into a single script rather than having two separate ones in Milestone03.

We will be updating the script to write out the `.csv` extension for consistency and clarity in the milestone04
