### ISSUE TITLE
proposal notes

### ISSUE THREAD

**Issue by HJMcSorley** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#42]
Hi @jimmyliu1326 👋 

here's  a loose outline of the proposal notes (let me know if you've got edits or notes and I'll improve this draft) 👍 

# Dashboard Proposal

## Description

Our app will have a landing page that shows the distribution of person's education, age, sex, ethnicity as they relate to each other and annual net gain (monetary gains over employment income). These plots will likely be a combination of boxplots, violin plots and density ridge plots. Users will be able to compare the distribution of net income with other variables by scrolling down through the app interface. From a drop-down list, users will be able to filter the distribution display variables by census demographics (i.e. only show females, or specific ethnicities). Via a slider bar, users will be able to narrow the range of data displayed based on filterable variables (e.g., age, education level, average hours worked per week). 
This app will allow users to compare two variables such as education level, age, sex, hours works, ethnicity or annual net gain, and also to rank personal attributes relative to whether annual income is predicted to be above or below $50,000.
 
## Usage Scenario

Pat is interested in understanding how personal attributes and socioeconomic position are associated with annual financial gains. They want to [explore] a census dataset to [compare] attributes (e.g., age, sex, marital status, education and work hours) with annual net gain amounts to [identify] patterns relating monetary benefits to personal and socioeconomic details. When Pat logs on to the “1994 Adult Income Census Data App”, they will see an overview of all the available variables in the dataset, according to the number of instances (persons) associated with each demographic category. They can filter variables to narrow the range of personal attributes to compare to net annual gains, and/or rank census participants according to their predicted annual income (over or under $50K). 
When Pat does so, they may notice that there do not appear to be obvious links between the available personal attributes and net annual gain. They may also notice that the data is dominated by a specific demographic, which may encourage them to pursue the collection of more representative and diverse demographic data in future census.

**Comment by jimmyliu1326** [comment]
Hi Hannah,

Thanks for writing up the proposal! I think it is really well written overall.

Some comments:

* For the third sentence under `Description`, I would be a bit more specific by saying:
```
Users will be able to compare the distribution of net income with other variables through toggling between different explanatory variables to visualize their effects on net income.
```
* For the fourth sentence under `Description`, I would change the wording a little by saying:
```
From a drop-down list, users will be able to select between different demographic variables to visualize the metadata distribution of the census participants.
```

**Comment by HJMcSorley** [comment]
Hi Jimmy, 
Sounds good. I'll make adjustments. Thanks!

**Comment by HJMcSorley** [comment]
completed
