### ISSUE TITLE
Add vectorized code

### ISSUE THREAD

**Issue by jimmyliu1326** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#43]
Vectorize the generation of plots

Priority: Low
Source: https://github.com/STAT547-UBC-2019-20/group_08_ADULT-INCOME/issues/33#issue-583363404

**Comment by HJMcSorley** [comment]
This low priority task was not included in the enhancements we made. The generation of plots was completed without loops or other inefficient processes, therefore we did not augment the plots to be vectorized.
