### ISSUE TITLE
Add discussion/conclusion section to final report

### ISSUE THREAD

**Issue by jimmyliu1326** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#44]
Write up a short paragraph discussing our findings

Priority: Medium

Source: https://github.com/STAT547-UBC-2019-20/group_08_ADULT-INCOME/issues/38#issue-585397717

**Comment by HJMcSorley** [comment]
I'll work on this :)

**Comment by HJMcSorley** [comment]
complete
